var objects = [
  {
    name: "Toast",
    id: "0",
    themes: ["food"],
    colors: ["yellow"],
  },
  {
    name: "Bell",
    id: "1",
    themes: ["sound", "church", "object"],
    colors: ["gold"],
  },
  {
    name: "Gun",
    id: "2",
    themes: ["weapon", "object"],
    colors: ["silver"],
  },
  {
    name: "Scroll",
    id: "3",
    themes: ["paper", "writing", "object"],
    colors: ["yellow"],
  },
  {
    name: "Amulet",
    id: "4",
    themes: ["jewelry", "object"],
    colors: ["gold", "cyan"],
  },
  {
    name: "Ring",
    id: "5",
    themes: ["jewelry", "object"],
    colors: ["gold"],
  },
  {
    name: "Red Gem",
    id: "6",
    themes: ["jewelry", "object"],
    colors: ["red"],
  },
  {
    name: "Green Gem",
    id: "7",
    themes: ["jewelry", "object"],
    colors: ["green"],
  },
  {
    name: "Scroll 2",
    id: "8",
    themes: ["paper", "writing", "object"],
    colors: ["brown"],
  },
  {
    name: "Fishing Rod",
    id: "9",
    themes: ["food", "tools", "object"],
    colors: ["brown"],
  },
  {
    name: "Axe",
    id: "10",
    themes: ["weapon", "object"],
    colors: ["brown", "silver"],
  },
  {
    name: "Shell",
    id: "11",
    themes: ["animals"],
    colors: ["brown"],
  },
  {
    name: "Plant",
    id: "12",
    themes: ["plants"],
    colors: ["brown", "green"],
  },
  {
    name: "Glove",
    id: "13",
    themes: ["clothing", "armour", "object"],
    colors: ["gray"],
  },
  {
    name: "Flower",
    id: "14",
    themes: ["plants"],
    colors: ["white"],
  },
  {
    name: "Scroll 3",
    id: "15",
    themes: ["paper", "writing", "object"],
    colors: ["white", "brown"],
  },
  {
    name: "Box",
    id: "16",
    themes: ["container", "object"],
    colors: ["brown"],
  },
  {
    name: "Blue Gem",
    id: "17",
    themes: ["jewelry", "object"],
    colors: ["blue"],
  },
  {
    name: "Red Potion",
    id: "18",
    themes: ["consumable", "object"],
    colors: ["red"],
  },
  {
    name: "Red Choker",
    id: "19",
    themes: ["jewelry", "object"],
    colors: ["red"],
  },
  {
    name: "Blue Book",
    id: "20",
    themes: ["paper", "writing", "object"],
    colors: ["blue"],
  },
  {
    name: "Teeth",
    id: "21",
    themes: ["bodyparts"],
    colors: ["red", "white"],
  },
  {
    name: "Blue Mushroom",
    id: "22",
    themes: ["food", "plants"],
    colors: ["blue"],
  },
  {
    name: "Red Mushroom",
    id: "23",
    themes: ["food", "plants"],
    colors: ["red", "white"],
  },
  {
    name: "Blue Gloves",
    id: "24",
    themes: ["clothing", "armour"],
    colors: ["blue"],
  },
  {
    name: "Bucket",
    id: "25",
    themes: ["water", "container", "object"],
    colors: ["blue", "brown"],
  },
];